---
title: "p8105_hw6_qw2331"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%",
  message = FALSE,
  warning = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

### 1.1 Load the data
```{r data import}
baby_bwt_raw <- 
  read_csv("./data/birthweight.csv")
```

### 1.2 Clean the data
```{r data clean}
# Convert numeric to factor
race <- c("White", "Black", "Asian", "Puerto Rican", "Other", "Unkown")

baby_bwt_df <- 
  baby_bwt_raw %>% 
  mutate(
    babysex = factor(recode(babysex, `1` = "male", `2` = "female")),
    malform = factor(recode(malform, `0` = "absent", `1` = "present")),
    frace = factor(race[frace]),
    mrace = factor(race[mrace])
  )
```

### 1.3 Propose a regression model

**1.3.1 Check distribution of target variable `brithweight`**
```{r}
baby_bwt_df %>% 
  ggplot(aes(bwt)) + 
  geom_histogram(aes(y = ..density..), fill = "orange", alpha = .6) +
  geom_density(alpha = .4) + 
  labs(
    title = "Density of birthweight",
    x = "Birth Weight (grams)",
    y = "Density"
  )
```

**1.3.2 Summary statistics and check outliers**
```{r}
# Check for missing values and a brief data review
summary(baby_bwt_df)
str(baby_bwt_df)

# Check outliers using boxplots
pivotdata <- 
  baby_bwt_df %>% 
  select(2:6, 8, 10:12, 17:18, 20) %>% 
  pivot_longer(
    everything(),
    names_to = "variable",
    values_to = "value"
  )

pivotdata %>% 
  ggplot(aes(factor(variable), value)) + 
  geom_boxplot(
    aes(color = variable), 
    show.legend = FALSE, outlier.size = .8) + 
  facet_wrap(~variable, scale = "free") + 
  labs(
    title = "Boxplots of 12 numeric variables",
    x = "Variable",
    y = "Value"
  )
```

**1.3.3 Correlation Matrix**
```{r}
# Create a correlation matrix
cordata <- 
  baby_bwt_df %>% 
  select(2:6, 8, 10:12, 17:18, 20) %>% 
  cor() %>% 
  round(3)

ggcorrplot::ggcorrplot(
  cordata, type = "lower", hc.order = TRUE, lab = TRUE, lab_size = 3) + 
  guides(
    fill = guide_legend(title = "Pearson\nCorrelation")
  )
```

